### PR TITLE
fixed macOS vibrancy (fixes #54; fixes #55)

### LINKED ISSUE #54: Not working on macOS Big Sur
No apparent effect on macOS Big Sur. I've tried various combinations of settings and poked through the source, but cannot get any sort of vibrancy (blurred background) effect.

**To Reproduce**
1. Run [this gist](https://gist.github.com/jcarpenter/cb82819c602eb08f0d5b14d805858a45) in Electron Fiddle, on macOS Big Sur.

**Expected behavior**
A vibrancy effect in the background of the window.

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Electron: Tested both `9.4.0` and `11.1.1`. 
 - Glasstron: 0.0.5

**Additional context**

* This is on a 2019 MacBook Pro 15". 
* Standard vibrancy works. Albeit with a noticeable performance hit.
* I've closely reviewed the docs, but am still a little unclear on what configuration setting to use for macOS. The following is what the gist uses:

```js
const win = new glasstron.BrowserWindow({
  width: 800,
  height: 600,
  backgroundColor: 'transparent',
  // vibrancy: 'sidebar',
  // titleBarStyle: 'hiddenInset',
  transparent: true,
  webPreferences: {
    nodeIntegration: true
  }
});

// win.blurType = "sidebar";
win.setVibrancy('sidebar')
win.setBlur(true);
```

### LINKED ISSUE #55: setVibrancy() broken on macOS
```
const { BrowserWindow: GBW } = require('glasstron')
const { app, BrowserWindow: EBW } = require('electron')

app.on('ready', () => {
    let w1 = new GBW({})
    let w2 = new EBW({})
    w1.setVibrancy('fullscreen-ui')
    w2.setVibrancy('fullscreen-ui')
})
```

### PR DESCRIPTION
**Pull request by Eugeny**

### CODE REVIEW

**Comment by AryToNeX** [comment]
This reflects the intended behaviour fully, right??

**Comment by Eugeny** [comment]
Yeah, if I got it right, you want `setVibrancy` to set and remember the value and `setBlur` to toggle it afterwards.

**Comment by AryToNeX** [comment]
> Yeah, if I got it right, you want `setVibrancy` to set and remember the value and `setBlur` to toggle it afterwards.

the idea was "fixing" electron's shortcomings by remembering the last vibrancy state and eventually spitting it out via `win.vibrancy`; but `getBlur()` should be the only way to know if the blur occurs or not (across all OSes)

**Comment by AryToNeX** [comment]
whatever, I am merging this then

**Pull request merged**
